### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by TomWilsonCoder** [Lipsis/Lipsis#2]
Before we write the CSS parser, we MUST have unicode support in the MarkupParser. At the moment, it only supports ASCII (8bits wide) and not Unicode (16bits wide).

**Comment by TomWilsonCoder** [comment]
Added support for UTF-8 on MarkupParser, it only decodes inner text on tags as UTF-8 since tags and tag names are going to be ASCII.

**Comment by thecodertom** [comment]
Added support for caller to use custom encoding for parsing
